//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisposeList
    {
        public int AUTOID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<System.DateTime> DisposeDate { get; set; }
        public Nullable<bool> IsDisposed { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
