//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.PhoneDongles = new HashSet<PhoneDongle>();
        }
    
        public int AUTOID { get; set; }
        public string ProviderName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<PhoneDongle> PhoneDongles { get; set; }
    }
}
