//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitType
    {
        public UnitType()
        {
            this.Computers = new HashSet<Computer>();
            this.ModelTypes = new HashSet<ModelType>();
            this.PhoneDongles = new HashSet<PhoneDongle>();
            this.VOIPs = new HashSet<VOIP>();
        }
    
        public int UnitTypeID { get; set; }
        public string UnitTypeName { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual ICollection<Computer> Computers { get; set; }
        public virtual ICollection<ModelType> ModelTypes { get; set; }
        public virtual ICollection<PhoneDongle> PhoneDongles { get; set; }
        public virtual ICollection<VOIP> VOIPs { get; set; }
    }
}
